---
- hosts: geodatagov23
  user: ubuntu
  sudo: yes
  tasks:

    - name: make sure packages are installed
      action: apt pkg={{item}} state=installed
      with_items:
        - htop
        - atool
        - ruby
        - python-virtualenv
        - python-setuptools
        - git
        - python-dev
        - ruby-dev
        - postgresql-client
        - libxml2-dev
        - libxslt-dev
        - bison
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-selinux
        - wget
        - vim
        - python-psycopg2
        - libpq-dev
        - libgeos-c1

#CKAN setup
    - name: remove old code
      action: file path=/usr/lib/ckan/src state=absent

    - name: get ckan version
      action: git repo=https://github.com/ckan/ckan.git dest=/usr/lib/ckan/src/ckan version=ckan-2.3

    - name: get pip
      action: easy_install name=https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz

    - name: install requirements and make virtualenv
      action: pip requirements=/usr/lib/ckan/src/ckan/requirements.txt virtualenv=/usr/lib/ckan/ virtualenv_site_packages=yes

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/src/ckan/ ../../bin/python setup.py develop

    - name: get geodatagov
      action: git repo=https://github.com/GSA/ckanext-geodatagov.git dest=/usr/lib/ckan/src/ckanext-geodatagov version=ubuntu-install-ckan23

    - name: install requirements for geodatagov
      action: pip requirements=/usr/lib/ckan/src/ckanext-geodatagov/pip-requirements.txt virtualenv=/usr/lib/ckan/

    - name: run setup.py develop for geodatagov
      action: command chdir=/usr/lib/ckan/src/ckanext-geodatagov/ ../../bin/python setup.py develop

    - name: install requirements for harvest
      action: pip requirements=/usr/lib/ckan/src/ckanext-harvest/pip-requirements.txt virtualenv=/usr/lib/ckan/

    - name: install requirements for spatial
      action: pip requirements=/usr/lib/ckan/src/ckanext-spatial/pip-requirements.txt virtualenv=/usr/lib/ckan/

    - name: get datajson extension
      action: git repo=https://github.com/GSA/ckanext-datajson dest=/usr/lib/ckan/src/ckanext-datajson version=master

    - name: use a good version of jsonschema
      replace: dest=/usr/lib/ckan/src/ckanext-datajson/pip-requirements.txt regexp='^jsonschema$' replace='jsonschema==2.4.0'
    - name: install requirements for datajson
      action: pip requirements=/usr/lib/ckan/src/ckanext-datajson/pip-requirements.txt virtualenv=/usr/lib/ckan/

    - name: run setup.py develop for datajson
      action: command chdir=/usr/lib/ckan/src/ckanext-datajson/ ../../bin/python setup.py develop

    - name: install requests 2.4.0
      action: pip name=requests version=2.4.0 virtualenv=/usr/lib/ckan/ 
    - name: install repoze.who 2.0
      action: pip name=repoze.who version=2.0 virtualenv=/usr/lib/ckan/ 
    - name: install new geoalchemy
      action: command chdir=/usr/lib/ckan/src/ckanext-geodatagov/ ../../bin/pip install -e  git+https://github.com/chokoswitch/geoalchemy.git@master#egg=geoalchemy

    - name: set permissions of ogc viewer
      shell: "chmod 777 -R /usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/"


    - name: remove psycopg2
      action: pip name=psycopg2 virtualenv=/usr/lib/ckan/ state=absent

    - name: create directories
      action: file path={{item}} state=directory
      with_items:
        - /etc/ckan

    - name: default apache removed
      action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent

    - name: copy all needed files
      action: copy src={{item}} dest=/{{item}}
      with_items:
        - etc/ckan/who.ini
        - etc/ckan/apache.wsgi
        - etc/ckan/production.ini
        - etc/apache2/sites-enabled/ckan.conf
        - etc/ckan/robots.txt

    - name: copy executables
      action: copy src={{item}} dest=/{{item}} mode=744
      with_items:
        - usr/bin/ckan

    - name: Apache | Enable some required modules
      action: command a2enmod rewrite headers 
      tags: common

    - name: use disallowed robots.txt
      shell: "cp /etc/ckan/robots.txt /usr/lib/ckan/src/ckan/ckan/public/"


##
## install a new version of libxml - needs to be greater than 2.9 for spatial plugin
##
     
#   # - name: Download libxml2-2.9.2
#   #   command: creates=~/libxml2-2.9.2.tar.gz chdir=~/ wget -T 40  ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz

#    # - name: unpack libxml2-2.9.2
#    #   command: creates=~/libxml2-2.9.2/ chdir=~/ tar zxf libxml2-2.9.2.tar.gz

#    # - name: configure libxml2-2.9.2
#    #   command: creates=~/libxml2-2.9.2/Makefile chdir=~/libxml2-2.9.2/ ~/libxml2-2.9.2/configure --libdir=/usr/lib64

#    # - name: compile and install libxml2-2.9.2
#    #   command: creates=/usr/lib64/libxml2.so.2.9.2 chdir=~/libxml2-2.9.2/ make install


## #
## # missing Celery?
## #
##     - name: install Celery
##       action: pip name=Celery virtualenv=/usr/lib/ckan/

##     - name: point apache.wsgi to development.ini
##       action: command sed -i 's/production.ini/development.ini/g' /etc/ckan/apache.wsgi

# #pycsw setup
#     - name: get pycsw version
#       action: git repo=https://github.com/geopython/pycsw.git dest=/usr/lib/ckan/src/pycsw version=1.10.1

#     - name: run setup build for pycsw
#       action: command chdir=/usr/lib/ckan/src/pycsw/ ../../bin/python setup.py build

#     - name: run setup install for pycsw
#       action: command chdir=/usr/lib/ckan/src/pycsw/ ../../bin/python setup.py install

#     - name: install pyproj
#       action: pip name=pyproj virtualenv=/usr/lib/ckan/

#     - name: install geolinks
#       action: pip name=geolinks virtualenv=/usr/lib/ckan/

#     - name: copy pycsw configuration files
#       action: copy src={{item}} dest=/{{item}} mode=644
#       with_items:
#         - etc/ckan/pycsw-all.cfg
#         - etc/ckan/pycsw-collection.cfg
#         - etc/ckan/pycsw.wsgi

    - name: restart apache
      action: service name=apache2 state=restarted

